apiVersion: v1
kind: ConfigMap
metadata:
  name: tasks-config
data:
  TASKS_PORT: "8082"
  AUTH_GRPC_ADDR: "auth:50051"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "tasksdb"
  REDIS_ADDR: "redis:6379"
  LOG_LEVEL: "info"